language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
addons:
  sonarcloud:
    organization: "leandrosb"
    token:
      secure: "5b9ffc95dc9d342e51641458a017aba0574f8f62" 
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
  - coverage run --source=taskscheduler setup.py test
after_success:
  - coverage xml
 # Install deepsource CLI
  - curl https://deepsource.io/cli | sh
  # Report coverage artifact to 'test-coverage' analyzer
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml